<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <!-- Meta tags - informações de configuração da página -->
      <meta charset="UTF-8">
      <meta name="robots" content="index, follow">
      <meta http-equiv="X-UA-Compatible" content="ie-edge">
      <meta name="description" content="Alterar descrição">
      <meta name="author" content="Lucas, Gustavo, Wesllen">
      <meta name="viewport" content="width=device-width, intial-scale=1">
      <!-- Tags relacionadas ao estilo - Fontes e Ícones -->
      <link rel="stylesheet" href="/css/linea-ecommerce/styles.css">
      <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous"> -->
      <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet"> 
      <link rel="stylesheet" href="/node_modules/font-awesome/css/font-awesome.min.css">
      <!-- Tags relacionadas ao estilo - Internas -->
      <link rel="stylesheet" href="/css/style.css">
      <!-- Scripts Javascript -->
      <script src="/node_modules/jquery/dist/jquery.min.js"></script>
      <script src="/node_modules/jquery-mask-plugin/dist/jquery.mask.min.js"></script>
      <script src="/js/admin-panel.js"></script>

      <title><?php $this->getPageTitle('| SVEP')?></title>
   </head>
   <body class="body--gray body--padded">   
      <?php $this->displayMessage(true) ?>
      <div class="sidebar-menu">
         <div class="sidebar-menu__logo"></div>
         <a href="/admin/produtos" class="sidebar-menu__item"><i class="sidebar-menu__icon icon-ecommerce-bag"></i></a>
         <a class="sidebar-menu__item"><i class="sidebar-menu__icon icon-ecommerce-sales"></i></a>
         <a class="sidebar-menu__item"><i class="sidebar-menu__icon icon-ecommerce-wallet"></i></a>
         <a class="sidebar-menu__item"><i class="sidebar-menu__icon icon-ecommerce-creditcard"></i></a>
      </div>
      <div class="topbar">
         <div class="topbar__search">
            <span class="topbar__icon"></span>
            <input id="procurar" class="topbar__input" type="text" placeholder="Procurar ...">
            <!-- <label class="topbar__label" for="procurar">Procurar ...</label> -->
         </div>
         <div class="topbar__item">
            <div class="topbar__profile-pic">
               <img class="topbar__img" src="/img/cake.svg" alt=""><i class="fa fa-caret-down topbar__arrow-down js-arrow-down-button"></i>
               <ul class="topbar__nav-menu js-nav-menu">
                  <li><a href="/admin/produtos">Produtos</a></li>
                  <li><a href="/admin/fornecedores">Fornecedores</a></li>
                  <li><a href="/admin/curriculos">Certificados</a></li>
                  <span class="u-divisor"></span>
                  <li><a href="/login/sair" title="Sair da sessão atual de usuário">Sair</a></li>
               </ul>
            </div>
         </div>
      </div>
      <!--Conteudo-->
      <?php $this->content() ?>
      <!--Fim Conteudo-->
      <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script> -->
   </body>
</html>
