<?php session_start(); use Core\FlashMessage; ?>
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <!-- Meta tags - informações de configuração da página -->
      <meta charset="UTF-8">
      <meta name="robots" content="index, follow">
      <meta http-equiv="X-UA-Compatible" content="ie-edge">
      <meta name="description" content="Alterar descrição">
      <meta name="author" content="Lucas, Gustavo, Wesllen">
      <meta name="viewport" content="width=device-width, intial-scale=1">
      <!-- Tags relacionadas ao estilo - Fontes e Ícones -->
      <link rel="stylesheet" href="css/linea-basic/styles.css">
      <link rel="stylesheet" href="css/linea-ecommerce/styles.css">
      <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet"> 
      <!-- Tags relacionadas ao estilo - Internas -->
      <link rel="stylesheet" href="css/style.css">
      <!-- Scripts Javascript -->
      <script src="node_modules/jquery/dist/jquery.min.js"></script>
      <script src="node_modules/simple-slider/dist/simpleslider.min.js"></script>
      <script src="node_modules/jquery-mask-plugin/dist/jquery.mask.min.js"></script>
      <script src="js/app.js"></script>

      <title><?php $this->getPageTitle('| SVEP')?></title>
   </head>
   <body>
      <!--------------------------- Header ---------------------------->
      <div class="popup popup__overlay js-popup">
         <span class="popup__close-btn js-login-close"></span>
         <form class="popup__container login-form js-login-form" action="/login/verificar" method="POST">
            <div class="login-form__control-group">
               <label class="login-form__label">Usuário</label>
               <input class="login-form__input js-input-user" type="text" name="usuario">
            </div>
            <div class="login-form__control-group">
               <label class="login-form__label">Senha</label>
               <input class="login-form__input js-input-psw" type="password" name="password">
            </div>
            <span class="login-form__message js-login-form-message"></span>
            <button class="btn btn--blue login-form__button" type="submit">Entrar</button>
            <a href="/cadastro" class="login-form__link" type="submit">Registrar-se</a>
         </form>
      </div>
      <!--------------------------- Header ---------------------------->
      <header class="header">
         <!------------------------ Navbar ---------------------------->
         <nav class="header__navbar">
            <h3 class="header__brand">
               <img class="header__logo" src="img/cake.svg" alt="-">
            </h3>
            <ul class="header__nav">
               <li><a class="active" href="#">Home</a></li><!--
               --><li><a href="#">Produtos</a></li><!--
               --><li><a href="#">Sobre</a></li><!--
               --><li><a href="#">Contato</a></li>
            </ul>
            <div class="header__box-option header__box-option--1">
               <i class="header__cart-icon icon-ecommerce-cart"></i>
            </div>
            <div class="header__box-option header__box-option--2 js-login-open">
               <span class="header__box-text">Login</span>
            </div>
         </nav>
      </header>
      <!--Conteudo-->
      <?php $this->content() ?>
      <!--Fim Conteudo-->
      <script>
         $(document).ready(function() {
            const $loginForm = $(".js-login-form"),
                  $formMessage = $(".js-login-form-message"),
                  inputs = {
                     user: $(".js-input-user"),
                     password: $(".js-input-psw")
                  };


            const handleFormData = function(e) {
               e.preventDefault();

               $.ajax({
                  type: "POST",
                  url: "/login/verificar",
                  data: $(this).serialize(),
                  success: function(data) { handleUserLogin($.parseJSON(data)); },
                  error: function(jqXhr, textStatus, errorThrown) { showMessage("Erro: Não foi possível fazer login!") }
               });
            }

            const handleUserLogin = function(login) {
               if (!login.success) 
                  showMessage(login.message ? login.message : "");

               if (parseInt(login.nivel) === 1) location.reload();
               else if (parseInt(login.nivel) === 2) location.href = "/admin";
            }

            const showMessage = function(message) {
               $formMessage.text(message);
               $formMessage.addClass("shake");
               setTimeout(function() { $formMessage.removeClass("shake"); }, 310);
            }

            $loginForm.on("submit", handleFormData);
         });
      </script>
   </body>
</html>
