<span class="admin-panel__breadcrumb">Admin > Produto > Cadastro</span>
<section class="admin-content">
   <form class="form" method="POST" action="/produto/cadastrar" enctype="multipart/form-data">

      <div class="row">
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label" for="nome">Nome</label>
               <input id="nome" class="form__control" type="text" name="nome" required>
            </div>

            <div class="form__group">
               <label class="form__label" for="fabricante">Fabricante</label>
               <input id="fabricante" class="form__control" type="text" name="fabricante">
            </div>
            
            <div class="form__group">
               <label class="form__label" for="descricao">Descrição</label>
               <textarea id="descricao" class="form__control form__control--textarea" name="descricao"></textarea>
            </div>

            <div class="row no-gap">
               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="peso">Peso (kg)</label>
                     <input id="peso" class="form__control" type="text" name="peso">
                  </div>
               </div>

               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="valor-venda">Data de Validade</label>
                     <input id="data-validade" class="form__control" type="date" name="dataValidade">
                  </div>
               </div>
            </div>
         </div>

         <div class="col-1-of-2">
            <div class="row no-gap">
               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="valor-comprado">Valor comprado (R$)</label>
                     <input id="valor-comprado" class="form__control" type="text" name="valorComprado" required>
                  </div>
               </div>

               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="valor-venda">Valor de venda (R$)</label>
                     <input id="valor-venda" class="form__control" type="text" name="valorVenda" required>
                  </div>
               </div>
            </div>

            <div class="form__group">
               <label class="form__label" for="fornecedor">Fornecedor</label>
               <select id="fornecedor" class="form__control form__control--select" name="fornecedor">
                  <?php foreach($this->view->fornecedores as $fornecedor) : ?>
                     <option value="<?= $fornecedor->idFornecedor ?>">
                        <?= $fornecedor->nome ?>
                     </option>
                  <?php endforeach; ?>
               </select>
            </div>

             <div class="form__group">
               <div class="row">
                  <div class="col-1-of-2">
                     <label class="form__label" for="fornecedor">Imagem</label>
                     <input id="imagem" class="form__control" type="file" name="imagem">
                  </div>
                  <div class="col-1-of-2">
                     <label class="form__label" for="tipo-visibilidade">Visível pro cliente?</label>
                     <select id="tipo-visibilidade" class="form__control form__control--select" name="tipoVisibilidade">
                        <option value="0">Sim</option>
                        <option value="1">Não</option>
                     </select>
                  </div>
               </div>
            </div>
         </div>
      </div>

      <button class="btn btn--blue u-push-right" type="submit">Cadastrar &nbsp;<i class="fa fa-arrow-right"></i> </button>
   </form>
</section>