<form method="POST" action="/fornecedor/cadastrar">
   <input type="text" name="nome" placeholder="Nome">
   <input type="text" name="telefone" placeholder="Telefone">
   <input type="text" name="email" placeholder="E-mail">
   <input type="text" name="razaoSocial" placeholder="Razão Social">
   <input type="text" name="inscricaoEstadual" placeholder="Inscrição Estadual">

   <input type="text" name="cep" placeholder="CEP">
   <input type="text" name="endereco" placeholder="Endereço">
   <input type="text" name="complemento" placeholder="Complemento">
   <input type="text" name="numero" placeholder="Numero">
   <input type="text" name="bairro" placeholder="Bairro">
   <input type="text" name="cidade" placeholder="Cidade">
   <input type="text" name="uf" placeholder="UF">
   <input type="text" name="logradouro" placeholder="Logradouro">
   <button type="submit">Cadastrar</button>
</form>