<section class="admin-content">
      <table class="table">
      <thead>
         <tr>
            <th>Nome</th>
            <th>Telefone</th>
            <th>E-mail</th>
            <th>Razão Social</th>
            <th>Status</th>
            <th>Data Bloqueio</th>
            <th>Ins. Estadual</th>
         </tr>
      </thead>
      <tbody>
         <?php if ($this->view->fornecedores) :
               foreach ($this->view->fornecedores as $fornecedor): 
         ?>
         <tr>
               <td><?=$fornecedor->nome_fornecedor?></td>
               <td><?=$fornecedor->telefone?></td>
               <td><?=$fornecedor->email?></td>
               <td><?=$fornecedor->razaoSocial?></td>
               <td><?=$fornecedor->status?></td>
               <td><?=date("d/m/Y", strtotime($fornecedor->dataBloqueioFornecedor))?></td>
               <td><?=$fornecedor->inscricaoEstadual?></td>
               <td>
                   <a href = "<?= base_url('')?>/produto/editar?id=<?=$fornecedor->idFornecedor?>" ><i class = "fa fa-edit" style="border: 2px solid #C0C0C0; padding: 2%; border-radius: 5px; padding-top: 5px; padding-left: 5px;"></i></a>
                   <a href = "<?= base_url('')?>/produto/excluir?id=<?=$fornecedor->idFornecedor?>"><i class = "fa fa-close" style="border: 2px solid #C0C0C0; padding: 2%; border-radius: 5px; padding-top: 5px; padding-left: 5px; margin-left: 4%;"></i></a>
               </td>
         </tr>
         <?php    endforeach;
               endif;
         ?>
      </tbody>
   </table>

   <a href="/admin/cadastro/fornecedor" class="admin-content__plus-button u-margin-top-med">
      <i class="fa fa-plus"></i>
   </a>

</section>