<span class="admin-panel__breadcrumb">Admin > Fornecedores</span>
<section class="admin-content">
      <table class="table">
      <thead>
         <tr>
            <th>Nome</th>
            <th>Telefone</th>
            <th>E-mail</th>
            <th>Razão Social</th>
            <th>Status</th>
            <th>Data Bloqueio</th>
            <th>Ins. Estadual</th>
         </tr>
      </thead>
      <tbody>
         <?php if ($this->view->fornecedores) :
               foreach ($this->view->fornecedores as $fornecedor): 
         ?>
         <tr>
               <td><?=$fornecedor->nome?></td>
               <td><?=$fornecedor->telefone?></td>
               <td><?=$fornecedor->email?></td>
               <td><?=$fornecedor->razaoSocial?></td>
               <td><?=$fornecedor->status?></td>
               <td><?=date("d/m/Y", strtotime($fornecedor->dataBloqueioFornecedor))?></td>
               <td><?=$fornecedor->inscricaoEstadual?></td>
               <td class="table__toggler">
						<i class="fa fa-ellipsis-h"></i>
						<ul class="table__options-group">
								<li class="table__option"><a href="/admin/fornecedor/editar?id=<?=$fornecedor->idFornecedor?>"><i class="fa fa-pencil"></i> Editar</a></li>
								<li class="table__option"><a href="/admin/fornecedor/excluir?id=<?=$fornecedor->idFornecedor?>"><i class="fa fa-close"></i> Excluir</a></li>
						</ul>
					</td>
         </tr>
         <?php    endforeach;
               endif;
         ?>
      </tbody>
   </table>

   <a href="/admin/cadastro/fornecedor" class="admin-content__plus-button u-margin-top-med">
      <i class="fa fa-plus"></i>
   </a>

</section>