
<section class="admin-panel">
   <span class="admin-panel__breadcrumb">Admin > Dashboard</span>
   <div class="row">
      <div class="col-1-of-4">
      <div class="admin-panel__info-card admin-panel__info-card--1">
            <div class="admin-panel__info--main">
               <i class="fa fa-user admin-panel__icon"></i>
               <h3 class="admin-panel__caption">
                  Visitantes do Mês
               </h3>
            </div>
            <div class="admin-panel__info--sub">
               <div class="admin-panel__info--inner">
                  <h4 class="admin-panel__title">Acessos</h4>
                  <span class="admin-panel__content">
                     14 MIL
                  </span>
               </div>
            </div>
         </div>
      </div>
      <div class="col-1-of-4">
      <div class="admin-panel__info-card admin-panel__info-card--2">
            <div class="admin-panel__info--main">
               <i class="fa fa-dollar admin-panel__icon"></i>
               <h3 class="admin-panel__caption">
                  Receita Gerada
               </h3>
            </div>
            <div class="admin-panel__info--sub">
               <div class="admin-panel__info--inner">
                  <h4 class="admin-panel__title">Lucro</h4>
                  <span class="admin-panel__content">
                     R$ 1200,00
                  </span>
               </div>
               <div class="admin-panel__info--inner">
                  <h4 class="admin-panel__title">Total Gastos</h4>
                  <span class="admin-panel__content">
                     R$ 500,00
                  </span>
               </div>
            </div>
         </div>
      </div>
      <div class="col-1-of-4">
         <div class="admin-panel__info-card admin-panel__info-card--3">
            <div class="admin-panel__info--main">
               <i class="fa fa-paper-plane admin-panel__icon"></i>
               <h3 class="admin-panel__caption">
                  Pedidos Pendentes
               </h3>
            </div>
            <div class="admin-panel__info--sub">
               <div class="admin-panel__info--inner">
                  <h4 class="admin-panel__title">Quantidade</h4>
                  <span class="admin-panel__content">
                     14 Pedidos
                  </span>
               </div>
            </div>
         </div>
      </div>
      <div class="col-1-of-4">
         <div class="admin-panel__info-card admin-panel__info-card--4">
            <div class="admin-panel__info--main">
               <i class="fa fa-list admin-panel__icon"></i>
               <h3 class="admin-panel__caption">
                  Logs
               </h3>
            </div>
            <div class="admin-panel__info--sub">
               <div class="admin-panel__info--inner">
                  <h4 class="admin-panel__title">Registros</h4>
                  <span class="admin-panel__content">
                     123
                  </span>
               </div>
            </div>
         </div>
      </div>
   </div>

   <div class="row">
      <div class="col-2-of-4"></div>
      <div class="col-2-of-4"></div>
   </div>

   <div class="row">
      <div class="col-1-of-3"></div>
      <div class="col-2-of-3"></div>
   </div>
</section>