<section class="admin-content">
   <table class="table">
      <thead>
         <tr>
            <th>Nome</th>
            <th>Fabricante</th>
            <th>Peso</th>
            <th>Valor Venda</th>
            <th>Valor Comprado</th>
            <th>Data Validade</th>
         </tr>
      </thead>
      <tbody>
         <?php if ($this->view->produtos) :
                  foreach ($this->view->produtos as $produto): 
             $id = $produto->idProduto;
         ?>
            <tr>
               <td><?=$produto->nome?></td>
               <td><?=$produto->fabricante?></td>
               <td><?=$produto->peso?></td>
               <td><?=$produto->valorVenda?></td>
               <td><?=$produto->valorComprado?></td>
               <td><?=$produto->dataValidade?></td>
               <td class="table__toggler">
                  <i class="fa fa-ellipsis-h"></i>
                  <ul class="table__options-group">
                     <li class="table__option"><a href="<?= base_url('')?>/produto/editar?id=<?=$id?>"></a><i class="fa fa-pencil"></i> Editar</a></li>
                     <li class="table__option"><a href="<?=base_url('')?>/produto/excluir?id=<?=$id?>"></a><i class="fa fa-close"></i> Excluir</a></li>
                  </ul>
               </td>
            </tr>
            </tbody>
           
         <?php 
                  endforeach; 
               endif;
         ?>
      
   </table>
    
   <a href="/admin/cadastro/produto" class="admin-content__plus-button u-margin-top-med">
      <i class="fa fa-plus"></i>
   </a>
    
</section>

