
<div class="container">
    <form method="POST" action="cadastro/create">
    <label>Login:</label><br>
    <input type="tetx" name="login"><br>
    <label>Senha:</label><br>
    <input type="password" name="senha"><br>
    <label>Nome:</label><br>
    <input type="text" name="nome"><br>
    <label>CPF:</label><br>
    <input type="text" name="cpf"><br>
    <label>RG:</label><br>
    <input type="text" name="rg"><br>
    <label>Telefone:</label><br>
    <input type="tel" name="telefone"><br>
    <label>Email:</label><br>
    <input type="email" name="email"><br>
    <label>CEP:</label><br>
    <input type="text" name="cep"><br>
    <label>Endereço:</label><br>
    <input type="text" name="endereco"><br>
    <label>Complemento:</label><br>
    <input type="text" name="complemento"><br>
    <label>Numero:</label><br>
    <input type="number" name="numero"><br>
    <label>Bairro:</label><br>
    <input type="text" name="bairro"><br>
    <label>Cidade:</label><br>
    <input type="text" name="cidade"><br>
    <label>UF:</label><br>
    <input type="text" name="uf"><br>
    <label>Logradouro</label><br>
    <input type="text" name="logradouro"><br>
    <input type="Submit" name="cadastrar" value="Cadastrar">
</form>
</div>