<h1 class="heading heading--primary u-text-center u-margin-top-med">Nova Conta</h1>
<div class="form u-margin-top-med">
    <form method="POST" action="cadastro/create">
    <div class="form__group">
        <input class="form__control" type="tetx" name="login">
        <label class="form__label">Usuário:</label>
        <span class="form__border-bottom"></span>
    </div>
    <div class="form__group">
        <input class="form__control" type="password" name="senha">
        <label class="form__label">Senha:</label>
        <span class="form__border-bottom"></span>
    </div>
    <div class="form__group">
        <input class="form__control" type="password" name="confirmaSenha">
        <label class="form__label">Confirmar Senha:</label>
        <span class="form__border-bottom"></span>
    </div>
    <div class="form__group">
        <input class="form__control" type="text" name="nome">
        <label class="form__label">Nome:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="cpf" data-input="CPF">
        <label class="form__label">CPF:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="rg">
        <label class="form__label">RG:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="tel" name="telefone" data-input="telefone">
        <label class="form__label">Telefone:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="email" name="email">
        <label class="form__label">Email:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="cep" data-input="CEP">
        <label class="form__label">CEP:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="endereco">
        <label class="form__label">Endereço:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="complemento">
        <label class="form__label">Complemento:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="number" name="numero">
        <label class="form__label">Numero:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="bairro">
        <label class="form__label">Bairro:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="cidade">
        <label class="form__label">Cidade:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="uf">
        <label class="form__label">UF:</label>
        <span class="form__border-bottom"></span>
    </div>    
    <div class="form__group">
        <input class="form__control" type="text" name="logradouro">
        <label class="form__label">Logradouro</label>
        <span class="form__border-bottom"></span>
    </div>    
    <input type="Submit" name="cadastrar" value="Cadastrar">
</form>
</div>