<h1 class="heading heading--primary u-text-center u-margin-top-med">Nova Conta</h1>

<div class="form u-margin-top-med u-padding-x-big">

    <form method="POST" action="usuario/cadastrar">
        <div class="row">
            <div class="col-1-of-2">
                <div class="form__group">
                    <label class="form__label">Usuário:</label>
                    <input class="form__control" type="text" name="login" placeholder="Usuário">
                </div>
                <div class="form__group">
                    <label class="form__label">Senha:</label>
                    <input class="form__control" type="password" name="senha" placeholder="Senha">
                </div>
                <div class="form__group">
                    <label class="form__label">Confirmar Senha:</label>
                    <input class="form__control" type="password" name="confirmaSenha" placeholder="Confirme a senha">
                </div>
                <div class="form__group">
                    <label class="form__label">Nome:</label>
                    <input class="form__control" type="text" name="nome" placeholder="Nome">
                </div>    
                <div class="form__group">
                    <label class="form__label">CPF:</label>
                    <input class="form__control" type="text" name="cpf" data-input="CPF" placeholder="CPF">
                </div>    
                <div class="form__group">
                    <label class="form__label">RG:</label>
                    <input class="form__control" type="text" name="rg" placeholder="RG">
                </div>    
                <div class="form__group">
                    <label class="form__label">Telefone:</label>
                    <input class="form__control" type="text" name="telefone" data-input="telefone" placeholder="Telefone">
                </div>    
                <div class="form__group">
                    <label class="form__label">Email:</label>
                    <input class="form__control" type="email" name="email" placeholder="E-mail">
                </div>    
            </div>
            <div class="col-1-of-2">
                <div class="form__group">
                    <label class="form__label">CEP:</label>
                    <input class="form__control" type="text" name="cep" data-input="CEP" placeholder="CEP">
                </div>    
                <div class="form__group">
                    <label class="form__label">Endereço:</label>
                    <input class="form__control" type="text" name="endereco" placeholder="Endereço">
                </div>    
                <div class="form__group">
                    <label class="form__label">Complemento:</label>
                    <input class="form__control" type="text" name="complemento" placeholder="Complemento">
                </div>    
                <div class="form__group">
                    <label class="form__label">Numero:</label>
                    <input class="form__control" type="number" name="numero" placeholder="Número">
                </div>    
                <div class="form__group">
                    <label class="form__label">Bairro:</label>
                    <input class="form__control" type="text" name="bairro" placeholder="Bairro">
                </div>    
                <div class="form__group">
                    <label class="form__label">Cidade:</label>
                    <input class="form__control" type="text" name="cidade" placeholder="Cidade">
                </div>    
                <div class="form__group">
                    <label class="form__label">UF:</label>
                    <input class="form__control" type="text" name="uf" placeholder="UF">
                </div>    
                <div class="form__group">
                    <label class="form__label">Logradouro</label>
                    <input class="form__control" type="text" name="logradouro" placeholder="Logradouro">
                </div>    
            </div>
        </div>
        
        <button class="btn btn--blue form__button" type="submit">Cadastrar</button>
    </form>
</div>