   <!------------------- Slideshow Produtos -------------------->
   <section class="slider" data-simple-slider>
      <img src="img/bolo-casamento.jpg" alt="Bolo de casamento">
      <img src="img/festa-aniversario.jpg" alt="Aniversariante em festa de aniversário">
      <img src="img/presentes.jpg" alt="Bolo de casamento">
   </section>
   <!--------------------------- Main ---------------------------->
   <div class="main" role="Main">
      <section class="section-produtos">
         
      </section>
   </div>

   
