<!--------------------------- Header ---------------------------->
<header class="header">
   <!------------------------ Navbar ---------------------------->
   <nav class="header__navbar">
      <h3 class="header__brand">
         <img class="header__logo" src="#" alt="-">
         Brand
      </h3>
      <ul class="header__nav">
         <li><a href="#">Home</a></li>
         <li><a href="#">Produtos</a></li>
         <li><a href="#">Sobre</a></li>
         <li><a href="#">Contato</a></li>
      </ul>
      <div class="header__box-option">
         <i class="header__cart-icon icon-ecommerce-cart"></i>
      </div>
   </nav>
   <!------------------- Slideshow Produtos -------------------->
   <section class="slider">
      <div class="slider__slide js-slide"></div>
      <div class="slider__slide js-slide"></div>
      <div class="slider__slide js-slide"></div>
   </section>
</header>
<!--------------------------- Main ---------------------------->
<div class="main" role="Main">
   <section class="section-produtos">
      
   </section>
</div>
   
