<?php
session_start();
?>
<!-- TODO: Jogar layout padrão em outro arquivo para reutilização -->
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <!-- Meta tags - informações de configuração da página -->
      <meta charset="UTF-8">
      <meta name="robots" content="index, follow">
      <meta http-equiv="X-UA-Compatible" content="ie-edge">
      <meta name="description" content="Alterar descrição">
      <meta name="author" content="Lucas, Gustavo, Wesllen">
      <meta name="viewport" content="width=device-width, intial-scale=1.0">
      <!-- Tags relacionadas ao estilo - Fontes e Ícones -->
      <link rel="stylesheet" href="css/linea-basic/styles.css">
      <link rel="stylesheet" href="css/linea-ecommerce/styles.css">
      <!-- Tags relacionadas ao estilo - Internas -->
      <link rel="stylesheet" href="css/style.css">

      <title><?php $this->getPageTitle('| SVEP')?></title>
   </head>
   <body>
        <!--Conteudo-->
        <?php $this->content()?>
        <!--Fim Conteudo-->        
    </body>
</html>
