<section class="admin-content">
   <form class="form" method="POST" action="/certificado/cadastrar">
      <div class="row">
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label">Nome:</label>
               <input class="form__control" type="text" name="nome" placeholder="Nome">
            </div>    
            <div class="form__group">
               <label class="form__label">CPF:</label>
               <input class="form__control" type="text" name="cpf" data-input="CPF" placeholder="CPF">
            </div>    
            <div class="form__group">
               <label class="form__label">RG:</label>
               <input class="form__control" type="text" name="rg" placeholder="RG">
            </div>    
            <div class="form__group">
               <label class="form__label">Telefone:</label>
               <input class="form__control" type="text" name="telefone" data-input="telefone" placeholder="Telefone">
            </div>    
            <div class="form__group">
               <label class="form__label">Email:</label>
               <input class="form__control" type="email" name="email" placeholder="E-mail">
            </div>
         </div>

         <div class="col-1-of-2">

            <div class="row no-gap">
               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="data-inicio">Data Início Curso</label>
                     <input id="data-inicio" class="form__control" type="date" name="dataInicio">
                  </div>
               </div>
               <div class="col-1-of-2">
                  <div class="form__group">
                     <label class="form__label" for="data-fim">Data Fim Curso</label>
                     <input id="data-fim" class="form__control" type="date" name="dataFim">
                  </div>
               </div>
            </div>

            <div class="row no-gap">
               <div class="col-2-of-3">
                  <div class="form__group">
                     <label class="form__label" for="responsavel">Professor(a)</label>
                     <input id="responsavel" class="form__control" type="text" name="responsavel">
                  </div>
               </div>
               <div class="col-1-of-3">
                  <div class="form__group">
                     <label class="form__label" for="carga-horaria">Carga (H)</label>
                     <input id="carga-horaria" class="form__control" type="text" name="cargaHoraria">
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="row">
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label">CEP:</label>
               <input class="form__control" type="text" name="cep" data-input="CEP" placeholder="CEP">
            </div>    
            <div class="form__group">
               <label class="form__label">Endereço:</label>
               <input class="form__control" type="text" name="endereco" placeholder="Endereço">
            </div>    
            <div class="form__group">
               <label class="form__label">Complemento:</label>
               <input class="form__control" type="text" name="complemento" placeholder="Complemento">
            </div>    
            <div class="form__group">
               <label class="form__label">Numero:</label>
               <input class="form__control" type="number" name="numero" placeholder="Número">
            </div>
         </div>
         <div class="col-1-of-2">
            <div class="form__group">
               <label class="form__label">Bairro:</label>
               <input class="form__control" type="text" name="bairro" placeholder="Bairro">
            </div>    
            <div class="form__group">
               <label class="form__label">Cidade:</label>
               <input class="form__control" type="text" name="cidade" placeholder="Cidade">
            </div>    
            <div class="form__group">
               <label class="form__label">UF:</label>
               <input class="form__control" type="text" name="uf" placeholder="UF">
            </div>    
            <div class="form__group">
               <label class="form__label">Logradouro</label>
               <input class="form__control" type="text" name="logradouro" placeholder="Logradouro">
            </div>    
         </div>
      </div>
      <button class="btn btn--blue pull-right" type="submit">Registrar Certificado <i class="fa fa-arrow-right"></i></button>
   </form>
</section>
