<span class="admin-panel__breadcrumb">Admin > Certificados</span>
<section class="admin-content">
   <table class="table">
      <thead>
         <tr>
            <th>Aluno</th>
            <th>Responsavel</th>
            <th>Carga Horária</th>
            <th>Data Início</th>
            <th>Data Fim</th>
         </tr>
      </thead>
      <tbody>
		<?php 
			if ($this->view->certificados) :
				foreach ($this->view->certificados as $certificado): 
					$id = $certificado->idCertificado;
		?>
			<tr>
				<td><?=$certificado->nome?></td>
				<td><?=$certificado->responsavel?></td>
				<td><?=$certificado->cargaHoraria?> Hora(s)</td>
				<td><?=date("d/m/Y", strtotime($certificado->dataInicio))?></td>
				<td><?=date("d/m/Y", strtotime($certificado->dataFim))?></td>
				<td class="table__toggler">
					<i class="fa fa-ellipsis-h"></i>
					<ul class="table__options-group">
                  <li class="table__option"><a href="/admin/certificado/gerar/<?=$id?>"><i class="fa fa-eye"></i> Ver PDF</a></li>
						<li class="table__option"><a href="/admin/certificado/editar/<?=$id?>"><i class="fa fa-pencil"></i> &nbsp;&nbsp;Editar</a></li>
						<li class="table__option"><a href="/admin/certificado/excluir/<?=$id?>"><i class="fa fa-close"></i> &nbsp;Excluir</a></li>
					</ul>
				</td>
			</tr>
		<?php 
				endforeach; 
			endif;
		?>
		</tbody>
   </table>
    
   <a href="/admin/certificado/cadastro" class="admin-content__plus-button u-margin-top-med">
      <i class="fa fa-plus"></i>
   </a>
    
</section>

